<?php

return [
    'task_pending_1' => [
        'id' => 1,
        'title' => 'Task 1',
        'description' => 'Description 1',
        'content' => 'Content 1',
        'status' => 'pending',
        'due_at' => '2028-01-01',
        'created_at' => '2022-01-01',
        'updated_at' => '2022-01-01',
        'deleted_at' => null,
        'user_id' => 1,
        'assignee_id' => 1,
    ],
    'task_pending_2' => [
        'id' => 2,
        'title' => 'Task 2',
        'description' => 'Description 2',
        'content' => 'Content 2',
        'status' => 'pending',
        'due_at' => '2028-01-01',
        'created_at' => '2022-01-01',
        'updated_at' => '2022-01-01',
        'deleted_at' => null,
        'user_id' => 1,
        'assignee_id' => 1,
    ],
    'task_cancel_1' => [
        'id' => 3,
        'title' => 'Task 3',
        'description' => 'Description 3',
        'content' => 'Content 3',
        'status' => 'cancel',
        'due_at' => '2028-01-01',
        'created_at' => '2022-01-01',
        'updated_at' => '2022-01-01',
        'deleted_at' => null,
        'user_id' => 1,
        'assignee_id' => 1,
    ],
    'task_overdue_1' => [
        'id' => 4,
        'title' => 'Task 4',
        'description' => 'Description 4',
        'content' => 'Content 4',
        'status' => 'pending',
        'due_at' => '2022-01-01',
        'created_at' => '2022-01-01',
        'updated_at' => '2022-01-01',
        'deleted_at' => null,
        'user_id' => 1,
        'assignee_id' => 1,
    ],
    'task_deleted_1' => [
        'id' => 5,
        'title' => 'Task 5',
        'description' => 'Description 5',
        'content' => 'Content 5',
        'status' => 'deleted',
        'due_at' => '2022-01-01',
        'created_at' => '2022-01-01',
        'updated_at' => '2022-01-01',
        'deleted_at' => '2022-03-01',
        'user_id' => 1,
        'assignee_id' => 1,
    ],
    'task_completed_1' => [
        'id' => 6,
        'title' => 'Task 6',
        'description' => 'Description 6',
        'content' => 'Content 6',
        'status' => 'completed',
        'due_at' => '2028-01-01',
        'created_at' => '2022-01-01',
        'updated_at' => '2024-01-01',
        'deleted_at' => null,
        'user_id' => 1,
        'assignee_id' => 1,
    ],
];
